version: '3'
services:
  facade:
    build: ./services/facade
    image: loopback-example-facade/facade
    ports:
      - "3000:3000"
    links:
      # - account
      # - customer
      - transaction
      - core
      - auth
    depends_on:
      # - account
      # - customer
      - transaction
      - core
      - auth
    volumes:
      - ./services/facade:/usr/src/app
  # customer:
  #   build: ./services/customer
  #   image: loopback-example-facade/customer-service
  #   ports:
  #     - "3001:80"
  #   volumes:9
  #     - ./services/customer:/usr/src/app
  # account:
  #   build: ./services/account
  #   image: loopback-example-facade/account-service
  #   ports:
  #     - "3002:80"
  #   volumes:
  #     - ./services/account:/usr/src/app
  transaction:
    build: ./services/transaction
    image: loopback-example-facade/transaction
    environment:
      - PDT_TOKEN=pdt_token # YOUR_YENEPAY_PDT_TKEN
      - FRONTEND_URL=http://localhost:8080
      - SELLER_CODE=0123 # YOUR_YENEPAY_SELLER_CODE
    ports:
      - "3003:3000"
    volumes:
      - ./services/transaction:/usr/src/app
    depends_on:
      - payment-db
    links:
      - payment-db
  core:
    build: ./services/core
    image: loopback-example-facade/core
    ports:
      - "3001:3000"
    volumes:
      - ./services/core:/usr/src/app
    depends_on:
      - core-db
    links:
      - core-db
  auth:
    build: ./services/auth
    image: loopback-example-facade/auth
    ports:
      - "3002:3000"
    volumes:
      - ./services/auth:/usr/src/app
    depends_on:
      - auth-db
    links:
      - auth-db
  auth-db:
    image: mongo
    volumes:
      - ./data/auth-db:/data/db
    ports:
      - "27018:27017"
  im-db:
    image: mongo
    volumes:
      - ./data/im-db:/data/db
    ports:
      - "27019:27017"
  payment-db:
    image: mongo
    volumes:
      - ./data/payment-db:/data/db
    ports:
      - "27020:27017"
  core-db:
    image: mongo
    volumes:
      - ./data/core-db:/data/db
    ports:
      - "27021:27017"
