module.exports = async function (server) {
    try{
        await Promise.all([
            "AngularJS Developer",
            "Back End Developer",
            "Blockchain Developer",
            "C# Developer",
            "C++ Developer",
            "CSS Developer",
            "DevOps Engineer",
            "Ecommerce Developer",
            "Front End Developer",
            "Full Stack Developer",
            "Golang Developer",
            "HTML5 Developer",
            "Java Developer",
            "JavaScript Developer",
            "Machine Learning Expert",
            "Magento Developer",
            "Mobile App Developer",
            "Node.js Developer",
            "PHP Developer",
            "Python Developer",
            "React Native Developer",
            "React.js Developer",
            "Ruby Developer",
            "Ruby on Rails Developer",
            "Rust Developer",
            "Salesforce Developer",
            "Scala Developer",
            "Software Developer",
            "Software Engineer",
            "Vue.js Developer",
            "WordPress Developer",
            "Adobe Photoshop Expert",
            "AJAX Developer",
            "Android App Developer",
            "AngularJS Developer",
            "ASP.NET Specialist",
            "ASP.NET MVC Specialist",
            "Bootstrap Specialist",
            "C# Developers & Programmer",
            "C++ Programmers & Developer",
            "CSS Developer",
            "CSS3 Developer",
            "Graphic Designer",
            "HTML Developer",
            "HTML5 Developer",
            "iOS Developer",
            "Java Developer",
            "jQuery Developer",
            "MongoDB Developer",
            "MySQL Developer",
            "MySQL Programmer",
            "Node.js Developer",
            "PHP Developer",
            "Python Developer",
            "React.js Developer",
            "Responsive Web Designer",
            "Ruby Developers & Programmer",
            "Ruby on Rails Developer",
            "SEO Expert",
            "SQL Developer",
            "Web Designer",
            "Website Developer",
            "WordPress Developer"
        ].map(label => server.models.Skill.create({ label })))
    } catch(e) {
        
    }
}